spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/accounts
    username: teste
    password: teste
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  devtools:
    add-properties: false