CREATE TABLE accounts (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    document_number VARCHAR(255) NOT NULL UNIQUE,
    created_at timestamp NOT NULL,
    updated_at timestamp NULL,
    CONSTRAINT accounts_pk PRIMARY KEY (id)
);